function [] = label2mlf( filename1, filename2 )
% read a LABEL file generated by AUDACITY
% write a MLF file readable in HTK

[a, b, labelt] = textread(filename1,'%f %f %s');

xmin = a*1e7 ; % need to convert from seconds (in label) to 100ns (in mlf)
xmax = b*1e7 ;

% write the mlf file
fid2 = fopen(filename2,'w') ;
tmp=regexprep(filename1(end:-1:1),'lebal.','flm.','once');tmp=tmp(end:-1:1); % allows to replace just once, the last one
fprintf(fid2,'#!MLF!#\n"%s"\n',tmp);
for n=1:numel(xmin)
    fprintf(fid2,'%s %s %s 0\n',num2str(xmin(n)),num2str(xmax(n)),labelt{n});
end

% end the mlf file (always need a ".")
fprintf(fid2,'.\n');
fclose(fid2) ;
