function [] = mlf2label( filename1, filename2 )
% read a MLF file generated by HTK
% write a LABEL file readable in AUDACITY

fid1 = fopen(filename1,'r') ;
fid2 = fopen(filename2,'w') ;

tline = fgetl(fid1);
if numel( findstr(tline,'#!MLF!#') )==0, exit('not a mlf file'), end
tline = fgetl(fid1); % skip the line containing the filename (the second line)

tline = fgetl(fid1); % get the first line
stoploop=0;
%while isempty(strfind(tline,'.')) || strfind(tline,'.')>1 % stop when the last line is reached (it contains a single ".")
while stoploop==0
	a = sscanf(tline,'%s %*s %*s %*s') ;
	b = sscanf(tline,'%*s %s %*s %*s') ;
	c = sscanf(tline,'%*s %*s %s %*s') ;
	%fprintf(1,'%s\n',tline);
	%fprintf(1,'%d\t%d\t%s\n',a,b,c);
	%fprintf(1,'%s\t%s\t%s\n',num2str(str2num(a)*1e-7),num2str(str2num(b)*1e-7),char(c)');
	fprintf(fid2,'%s\t%s\t%s\n',num2str(str2num(a)*1e-7),num2str(str2num(b)*1e-7),char(c)');
	tline = fgetl(fid1);
    if strfind(tline,'.')
        if strfind(tline,'.')==1 % stop when the last line is reached (it contains a single ".")
            stoploop=1;
        end
    end
end

fclose(fid1) ;
fclose(fid2) ;
