function [] = mlf2textGrid( filename1, filename2 )
% read a MLF file generated by HTK
% write a TEXTGRID file readable in PRAAT

fid1 = fopen(filename1,'r') ;
fid2 = fopen(filename2,'w') ;

tline = fgetl(fid1);
if numel( findstr(tline,'#!MLF!#') )==0, exit('not a mlf file'), end
tline = fgetl(fid1); % skip the line containing the filename (the second line)

numsyl = 0 ; % count the number of syl in the .mlf file
maxlen = 0 ; % record the end of the last syllable, thus this is the length of the sound file
seglist = '' ; % store the string containaing all the segments

tline = fgetl(fid1); % get the first line
while findstr(tline,'.')>1 % stop when the last line is reached (it contains a single ".")
	numsyl = numsyl + 1 ;
	%[a b c d] = sscanf(tline,'%d %d %s %d',"C") ; % original for octave
	a = sscanf(tline,'%d %*d %*s %*d') ;
	b = sscanf(tline,'%*d %d %*s %*d') ;
	c = sscanf(tline,'%*d %*d %s %*d') ;
	%fprintf(1,'\t\tintervals [%s]:\n\t\t\txmin = %s\n\t\t\txmax = %s\n\t\t\ttext = "%s"\n',num2str(numsyl),num2str(a*1e-7),num2str(b*1e-7),c);
	%[seglist 'intervals [' num2str(numsyl) ']:xmin = ' num2str(a*1e-7) '\nxmax = ' num2str(b*1e-7) '\ntext = "' c '"\n' ] ;
	%seglist = [seglist sprintf('\t\tintervals [%s]:\n\t\t\txmin = %s\n\t\t\txmax = %s\n\t\t\ttext = "%s"\n',num2str(numsyl),num2str(a*1e-7),num2str(b*1e-7),c)] ; % original for octave
	seglist = [seglist sprintf('\t\tintervals [%s]:\n\t\t\txmin = %s\n\t\t\txmax = %s\n\t\t\ttext = "%s"\n',num2str(numsyl),num2str(a*1e-7),num2str(b*1e-7),char(c)')] ;
	tline = fgetl(fid1);
end
maxlen = b ;

% write the header to the file, knowing the number of syl NUMSYL and the max length MAXLEN
fprintf(fid2,'File type = "ooTextFile"\nObject class = "TextGrid"\n\nxmin = 0\nxmax = %s\ntiers? <exists>\nsize = 1\nitem []:\n    item [1]:\n        class = "IntervalTier"\n        name = "syl"\n        xmin = 0\n        xmax = %s\n        intervals: size = %g\n',num2str(maxlen*1e-7),num2str(maxlen*1e-7),numsyl) ;
% write the list of the segments
%fprintf(1,'File type = "ooTextFile"\nObject class = "TextGrid"\n\nxmin = 0\nxmax = %s\ntiers? <exists>\nsize = 1\nitem []:\n    item [1]:\n        class = "IntervalTier"\n        name = "syl"\n        xmin = 0\n        xmax = %s\n        intervals: size = %g\n',num2str(maxlen*1e-7),num2str(maxlen*1e-7),numsyl);
%fprintf(1,'%s\n',seglist);
fprintf(fid2,seglist) ;

fclose(fid1) ;
fclose(fid2) ;
