function [] = raven2mlf( filename1, filename2 )
% read a file generated by RAVEN
% write a MLF file readable in HTK


[textname a b] = textread(filename1,...
    '%*f %s %*s %*f %f %f %*f %*f','headerlines',1);

% raven inserts a row for wavform and a row for spectrogram
if a(1)==a(2) && b(1)==b(2)
    a = a(1:2:end) ; 
    b = b(1:2:end) ;
    textname = textname(1:2:end) ;
end

xmin = a*1e7 ; % need to convert from seconds (in TextGrid) to 100ns (in mlf)
xmax = b*1e7 ;

% write the mlf file
fid2 = fopen(filename2,'w') ;
tmp=regexprep(filename1(end:-1:1),'nevar.','flm.','once');tmp=tmp(end:-1:1); % allows to replace just once, the last one
fprintf(fid2,'#!MLF!#\n"%s"\n',tmp);
for n=1:numel(xmin)
    fprintf(fid2,'%s %s %s 0\n',num2str(xmin(n)),num2str(xmax(n)),textname{n});
end

% end the mlf file (always need a ".")
fprintf(fid2,'.\n');
fclose(fid2) ;
