function [ mfccmat ] = readmfcc( filename, nl )
% read a file containing MFCC generated by HTK:
% HList -C config -o -h -t -i 9 file.wav >> filename

fid = fopen(filename,'r') ;

if (nargin<2) 
    nl=9;
end

% first find the size of the vectors and the number of samples
while 1
    tline = fgetl(fid);
    if ~ischar(tline),   break,   end
    if regexp(tline,'-* Target -*')
        fgetl(fid);break;
    end
end
values = textscan(fid, '%*s %*s %f %*s %*s %*f %*s\n%*s %*s %f %*s %*s %*s') ;
vecs = values{1} ;
numsample = values{2} ;

% go until the beginning of the data
while 1
    tline = fgetl(fid);
    if ~ischar(tline),   break,   end
    if regexp(tline, '-* Samples: .* -*')
        break;
    end
end

% fill the matrix with the data
mfcc = cell(vecs,numsample) ;
for n=1:numsample
%     patt = ['%*f %*c %f %f %f %f %f %f %f %f %f\n' ...
%                     '%f %f %f %f %f %f %f %f %f\n' ...
%                     '%f %f %f %f %f %f %f %f %f\n' ...
%                     '%f %f %f %f %f %f %f %f %f\n' ...
%                     '%f %f %f\n'] ;
    patt = '%*f %*c' ;
    for v=1:vecs
        patt=[patt ' %f'];
        if mod(v,nl)==0 patt=[patt '\n']; end
    end
    mfcc(:,n) = textscan(fid, patt, 1);
end

fclose(fid);
mfccmat = cell2mat(mfcc);

end