function [] = textGrid2mlf( filename1, filename2 )
% read a TEXTGRID file generated by PRAAT
% write a MLF file readable in HTK

fid1 = fopen(filename1,'r') ;
fid2 = fopen(filename2,'w') ;

tline = fgetl(fid1);
if numel( findstr(tline,'"ooTextFile"') )==0, exit('not a TextGrid file'), end
tline = fgetl(fid1);
if numel( findstr(tline,'"TextGrid"') )==0, exit('not a TextGrid file'), end

while numel(findstr(tline,'intervals [1]'))==0 % stop when the first interval is found
    tline = fgetl(fid1);
end

xmin = [] ;
xmax = [] ;
n = 1 ;
while feof(fid1) == 0 % stop at the end of the file
    tline = fgetl(fid1);
    deb = sscanf(tline,'%*s = %f') ;
    xmin = [xmin round(deb*1e7)] ; % need to convert from seconds (in TextGrid) to 100ns (in mlf)
    tline = fgetl(fid1);
    fin = sscanf(tline,'%*s = %f') ;
    xmax = [xmax round(fin*1e7)] ;
    tline = fgetl(fid1);
    type = sscanf(tline,'%*s = "%s"') ;
    textname{n} = type(1:end-1) ; % for some reason, the second " in the text is kept, so we need to skip it
    n = n+1 ;
    tline = fgetl(fid1); % skip the line with the interval number
end
fclose(fid1) ;

% write the mlf file
tmp=regexprep(filename1(end:-1:1),'dirGtxeT.','flm.','once');tmp=tmp(end:-1:1); % allows to replace just once, the last one
fprintf(fid2,'#!MLF!#\n"%s"\n',tmp);
for n=1:numel(xmin)
    fprintf(fid2,'%s %s %s 0\n',num2str(xmin(n)),num2str(xmax(n)),textname{n});
end

% end the mlf file (always need a ".")
fprintf(fid2,'.\n');
fclose(fid2) ;
